### ISSUE TITLE
Guess the Music !oq Komut Mesaj Önerisi

### ISSUE THREAD

**Issue by qreardedwastakennN** [guessthemusic/suggestions-and-bugs#1]
**!optionguess Komutu kullanıldığında 1 kez müzik çalıyor, ancak müzik tahmini yapıldığında 3 saniye sonra yeni bir müzik çalacak gibi bir mesaj kullanılıyor. Minimum !oq 1 komutu kullanmadan bu mesaj kaldırılmalı.**

## Ekler
![Screenshot_20210317-133002~2.png](https://user-images.githubusercontent.com/78941156/111453761-fa217080-8724-11eb-84da-76dbfff4eee4.png)

**Comment by MertBhey** [comment]
Aynı mesaj musicquiz komutunda da bulunuyor, farklı bir düzeltme yöntemi yakın zamanda uygulanacaktır.

**Comment by MertBhey** [comment]
Düzeltildi
