### ISSUE TITLE
Daha fazla şarkı lazım

### ISSUE THREAD

**Issue by yankesss369** [guessthemusic/suggestions-and-bugs#10]
Aga şarkı eklemek bu kadar zor değil niye sürekli aynı şarkıları duyuyoruz. Şu liste iyi mesela 
https://open.spotify.com/playlist/54aCJozfOfts89tlc9JJZC?si=e680ceaa203b4f44

**Comment by Ayemnatokey** [comment]
40 yıllık aşçıyım böyle çorba görmedim.

**Comment by MertBhey** [comment]
Botta yaklaşık olarak 1.100 şarkı bulunuyor, bunun haricinde de önerdiğiniz oynatma listesi oldukça karışık, yine de listeme ekledim. Teşekkürler
