### ISSUE TITLE
Guess the Music Veri Silme Hatası

### ISSUE THREAD

**Issue by qreardedwastakennN** [guessthemusic/suggestions-and-bugs#12]
# Hata Açıklaması
`Evet bir sunucuda skor tablosunu sıfırlamak istedim ancak sıfırlamak isterken bir hatayla karşılaştım. Alttaki fotoğraf gayet açıklayıcı duruyor gibi.`

# Ekler
![Screenshot_20210412-211431~2.png](https://user-images.githubusercontent.com/78941156/114441855-9039a100-9bd4-11eb-9d68-f795befdf9e6.png)

**Comment by qreardedwastakennN** [comment]
Üstteki fotoğrafın üstünde skor tablosu komutu kullanıyorum. Fotoğraf devamında üstteki fotoğraf devam ediyor. Ayrıca sunucudan kaynaklı olup olmadığını kontrol ettim ve başka bir sunucuda daha oluştu.

![Screenshot_20210412-211924~2.png](https://user-images.githubusercontent.com/78941156/114442198-fa524600-9bd4-11eb-8b8c-8f9f7a9c2bb1.png)

![Screenshot_20210412-212136~2.png](https://user-images.githubusercontent.com/78941156/114442452-3c7b8780-9bd5-11eb-8850-d1e89de0e9fd.png)

**Comment by MertBhey** [comment]
!reset server score/config
!reset me server/score

yardımdaki örnek kullanımı düzenleyeceğim
