### ISSUE TITLE
Ability to import own spotify playlists

### ISSUE THREAD

**Issue by queeenn** [guessthemusic/suggestions-and-bugs#15]
For example

I want the songs played to be in this playlist
https://open.spotify.com/playlist/37i9dQZEVXbLRQDuF5jeBp?si=32e4c4bd24884368

So it would work like this

User: !addplaylist https://open.spotify.com/playlist/37i9dQZEVXbLRQDuF5jeBp?si=32e4c4bd24884368 
Bot: Added playlist to Slot 1. 
User: !musicquiz 1
Bot then joins voice chat and plays clips of the songs in that playlist in a randomized order

**Comment by MertBhey** [comment]
This thing is in closed beta rn, i hope we'll release the update soon

**Comment by MertBhey** [comment]
Added it about a week ago, i forgot to update here sorry
