### ISSUE TITLE
Guess the Music Dil Seçimi

### ISSUE THREAD

**Issue by qreardedwastakennN** [guessthemusic/suggestions-and-bugs#2]
**Guess the Music dili sunucumda Türkçe ancak hala belirli yerleri ingilizce ve komutları hala ingilizce olarak kullanıyorum/kullanıyoruz. Bence dil seçiminde komut kullanımları değişmeli.**

## Ekler
![Screenshot_20210317-133610~2.png](https://user-images.githubusercontent.com/78941156/111454563-d1e64180-8725-11eb-8bff-27713d8ee1c4.png)

**Comment by MertBhey** [comment]
Tip mesajları hariç çoğu şeyin çevirisi dil dosyalarında mevcut, kodları düzenleyince çalışır hale getirilecektir.

**Comment by MertBhey** [comment]
Büyük oranda düzeltme sağlandı, kalan kısımlar zaman geçtikçe düzeltilecek
