### ISSUE TITLE
Buttons for !optionguess

### ISSUE THREAD

**Issue by HoppelHobbit** [guessthemusic/suggestions-and-bugs#30]
With the discord API supporting it, why doesn't the bot use buttons instead of users having to write letters? It just fills up the channel and takes longer on mobile

**Comment by Ayemnatokey** [comment]
![image](https://user-images.githubusercontent.com/64729369/149585055-13f7db8b-44a7-4852-bcef-b57b0bd94010.png)
We're working on it :)

**Comment by HoppelHobbit** [comment]
👍
