### ISSUE TITLE
Doğru Tahmin Mesajı

### ISSUE THREAD

**Issue by huseyinarsln** [guessthemusic/suggestions-and-bugs#4]
!q komutunda herhangi bir şarkıyı doğru tahmin ettikten sonra bot doğru tahmin mesajında kişiyi etiketlemek yerine mesajı yanıtlayabilir. (Anlamadıysan resime bakabilirsin)
![image](https://user-images.githubusercontent.com/46421933/111540892-c70cca80-8780-11eb-925c-2a2405c80275.png)

**Comment by MertBhey** [comment]
Kulağa mantıklı gibi geliyor, gelecek güncelleme ile eklenecektir

**Comment by Ayemnatokey** [comment]
Çok tatlı bir örnek bayıldım reis

**Comment by MertBhey** [comment]
Eklendi
