### ISSUE TITLE
Guess the Music !og Önerisi

### ISSUE THREAD

**Issue by qreardedwastakennN** [guessthemusic/suggestions-and-bugs#5]
**Aslında bu fikir/öneri nereden aklıma geldi uzun hikaye ancak bir yandan gereksiz olmasada olur ama bir yandan da olursa mükemmel olabilir diyebileceğim bir şey. Evet !og bize şıklı sistem üzerinden oyun sağlayabiliyor benim düşüncem ise a,b,c,d veya e diye yazacağımıza gönderilen şık mesajına tepkiler üzerinden yanıt vermemiz hatta şarkı geçileceği veya durdulacağı zamanda yine tepkiler üzerinden yönetmemiz. Şimdi gereksiz olmasada olur ancak dediğim gibi olursa mükemmel olabilir.**

**Herhangi bir ek eklenmedi.**

**Comment by Ayemnatokey** [comment]
Discord Rate Limit disconnected from the channel.

**Comment by MertBhey** [comment]
Quizin başlama sürecini uzatacağı gibi discord rate limitlerini de beraberinde getirilebilir, şu anlık eklenebilecek bir özellik değil
