### ISSUE TITLE
Tür önerisi

### ISSUE THREAD

**Issue by EnharAcikel** [guessthemusic/suggestions-and-bugs#9]
ben ve bazı kullanıcılarınız için önerim şu hangi tarz müzik çalabileceğini seçebilelim misal ben türkçe rap dinleyen birisiyim botun sadece türkçe rap çalmasını istiyorum öyle bir şey gelse çok güzel olur.

**Comment by MertBhey** [comment]
Yakın zamanda eklemek üzere uzun süredir üstünde çalışıyorum. Eklenildiğinde sunucuda etiket atılacaktır.

**Comment by MertBhey** [comment]
Kısa bir süre önce eklendi
